### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by baderababtain** [realzoulou/HomeAssistant-TP-Link-Tapo-Cloud#1]
Thank you for sharing your work ...
I am new to home assistant and could not figure out the problem I am facing.

I am facing a problem in adding the integration as it gives me the following error:

![image](https://user-images.githubusercontent.com/59815291/197305271-b0bd7569-15e5-47f5-a92c-4b1f1903127a.png)

Thank you for your help

**Comment by realzoulou** [comment]
I never saw this error message myself. "500 Internal Service error Server got itself in trouble" is not an error message from my Integration itself.
If you could enable all traces in both PyP100 (the most important dependency of this Integration) and this Integration itself, then I could have a look.

configuration.yaml

```
logger:
  default: warning
  logs:
    # log level for PyP100
    PyP100.PyP100: debug
    PyP100.PyP110: debug
    # log level for tplink_tapo_cloud
    custom_components.tplink_tapo_cloud: debug
    custom_components.tplink_tapo_cloud.sensor: debug
    custom_components.tplink_tapo_cloud.config_flow: debug
    custom_components.tplink_tapo_cloud.tapo_coordinator: debug




```
